# package the addon and create a release
name: Package and release

# launch on all tags
on:
  push:
    tags:
      - '**'

jobs:
  release:

    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # "GITHUB_TOKEN" is a secret always provided to the workflow
                                                 # for your own token, the name cannot start with "GITHUB_"

    steps:

      - name: Clone project
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # gets git history for changelogs

      - name: Package classic
        uses: BigWigsMods/packager@v2
        with:
          args: -g classic
